---
version: "3.7"

# This docker-compose file is used to build and test the container

services:
  starlink-exporter:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: felddy/starlink-exporter
    init: true
    restart: "no"
    # We want the container to fail to connect o Dishy during testing
    command: --address 192.168.100.100:9999
    ports:
      - target: 9817
        published: 19817  # Deconflict the prot during testing
        protocol: tcp
        mode: host

  starlink-exporter-version:
    # Run the container to collect version information
    image: felddy/starlink-exporter
    init: true
    restart: "no"
    command: --version
